---
permalink: iscsi-config-esxi/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, provision, lun, esx, host, computer 
summary: 'Usando a interface clássica do Gerenciador de sistema do ONTAP (ONTAP 9.7 e anterior), você pode configurar rapidamente o serviço iSCSI em uma máquina virtual de armazenamento (SVM), provisionar um LUN e disponibilizar o LUN usando um iniciador iSCSI em um computador host ESXi.' 
---
= Configuração iSCSI para ESXi usando visão geral do VSC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usando a interface clássica do Gerenciador de sistema do ONTAP (ONTAP 9.7 e anterior), você pode configurar rapidamente o serviço iSCSI em uma máquina virtual de armazenamento (SVM), provisionar um LUN e disponibilizar o LUN usando um iniciador iSCSI em um computador host ESXi.

Use este procedimento se:

* Você está usando o iniciador de software ESXi iSCSI nativo no ESXi 5.x.
* Não está a utilizar a autenticação CHAP para iSCSI.
* Você está usando uma versão suportada do Virtual Storage Console para VMware vSphere (VSC) para configurar as configurações de armazenamento para seu host ESX.
+
** A partir do VSC 7,0, o VSC faz parte do https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Ferramentas do ONTAP para VMware vSphere"^] dispositivo virtual, que inclui o VSC, o provedor vStorage APIs for Storage Awareness (VASA) e o Storage Replication Adapter (SRA) para os recursos do VMware vSphere.
** Certifique-se de que verifica o https://imt.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade do NetApp"^] para confirmar a compatibilidade entre as versões atuais do ONTAP e do VSC.


* Sua rede usa endereçamento IPv4.
* Você deseja atribuir endereços a interfaces lógicas usando qualquer um dos seguintes métodos:
+
** Automaticamente a partir de uma sub-rede definida
** Manualmente, usando um endereço selecionado de uma sub-rede existente
** Manualmente, usando um endereço que será adicionado a uma sub-rede existente


* Você tem pelo menos duas portas Ethernet de alta velocidade (1 GbE no mínimo, 10 GbE recomendados) disponíveis em cada nó no cluster.
+
As portas integradas UTA2 (também chamadas `CNA`) são configuráveis. Você configura essas portas na CLI do ONTAP; esse processo não é coberto no procedimento dele.

+
Consulte link:https://docs.netapp.com/us-en/ontap/networking/index.html["Gerenciamento de rede"^] para usar a CLI para configurar o controle de fluxo da porta Ethernet.

* Não está a configurar o arranque SAN iSCSI.
* Você está fornecendo armazenamento para VMs por meio do hipervisor ESXi e não executando um iniciador iSCSI na VM.


Para obter mais informações, consulte https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597: VMware vSphere for ONTAP"^] e a documentação da versão do VSC.
