---
permalink: iscsi-config-esxi/task_configuring_your_network_for_best_performance.html 
sidebar: sidebar 
keywords: ethernet, network, performance, iscsi, configuration, value, configure, configure your network for best performance 
summary: As redes Ethernet variam muito no desempenho. Pode maximizar o desempenho da rede utilizada para iSCSI selecionando valores de configuração específicos. 
---
= Configure a rede para obter o melhor desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As redes Ethernet variam muito no desempenho. Pode maximizar o desempenho da rede utilizada para iSCSI selecionando valores de configuração específicos.

.Passos
. Conete o host e as portas de armazenamento à mesma rede.
+
É melhor conetar-se aos mesmos interrutores. O roteamento nunca deve ser usado.

. Selecione as portas de velocidade mais alta disponíveis e dedique-as ao iSCSI.
+
As portas de 10 GbE são as melhores. As portas de 1 GbE são o mínimo.

. Desative o controle de fluxo Ethernet para todas as portas.
+
Você deve ver link:https://docs.netapp.com/us-en/ontap/networking/index.html["Gerenciamento de rede da ONTAP 9"] para usar a CLI para configurar o controle de fluxo da porta Ethernet.

. Ative quadros jumbo (normalmente MTU de 9000).
+
Todos os dispositivos no caminho de dados, incluindo iniciadores, destinos e switches, devem suportar quadros jumbo. Caso contrário, ativar quadros jumbo realmente reduz o desempenho da rede substancialmente.


