---
permalink: iscsi-config-esxi/task_deciding_where_to_provision_volume.html 
sidebar: sidebar 
keywords: provision, volume, lun, add, exist, storage, virtual, machine, svm, iscsi, decide where to provision the volume 
summary: Antes de provisionar um volume para conter LUNs, você precisa decidir se deseja adicionar o volume a uma máquina virtual de storage existente ou criar um novo SVM para o volume. Talvez você também precise configurar iSCSI em um SVM existente. 
---
= Decidir onde provisionar o volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de provisionar um volume para conter LUNs, você precisa decidir se deseja adicionar o volume a uma máquina virtual de storage (SVM) existente ou criar um novo SVM para o volume. Talvez você também precise configurar iSCSI em um SVM existente.

.Sobre esta tarefa
Se um SVM existente já estiver configurado com os protocolos necessários e tiver LIFs que podem ser acessados do host, será mais fácil usar o SVM existente.

É possível criar um novo SVM para separar dados ou administração de outros usuários do cluster de storage. Não há vantagem de usar SVMs separadas apenas para separar protocolos diferentes.



== Procedimento

* Se você quiser provisionar volumes em uma SVM que já esteja configurada para iSCSI, verifique se o serviço iSCSI está sendo executado.
+
link:task_verifying_iscsi_is_running_on_existing_vserver.html["Verificando se o serviço iSCSI está sendo executado em um SVM existente"]

* Se você quiser provisionar volumes em uma SVM existente que tenha iSCSI habilitado, mas não configurado, configure iSCSI no SVM existente.
+
link:task_configuring_iscsi_fc_creating_lun_on_existing_svm.html["Configuração do iSCSI em um SVM existente"]

+
Esse é o caso em que você não seguiu esse procedimento para criar o SVM ao configurar um protocolo diferente.

* Se você quiser provisionar volumes em uma nova SVM, link:task_creating_svm.html["Criar um novo SVM"].

