---
sidebar: sidebar 
permalink: reference_legal_notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais. 
---
= Avisos legais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Avisos legais fornecem acesso a declarações de direitos autorais, marcas registradas, patentes e muito mais.



== Direitos de autor

http://www.netapp.com/us/legal/copyright.aspx[]



== Marcas comerciais

NetApp, o logotipo DA NetApp e as marcas listadas na página de marcas comerciais da NetApp são marcas comerciais da NetApp, Inc. Outros nomes de produtos e empresas podem ser marcas comerciais de seus respetivos proprietários.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Patentes

Uma lista atual de patentes de propriedade da NetApp pode ser encontrada em:

https://www.netapp.com/us/media/patents-page.pdf[]



== Política de privacidade

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Código aberto

Fornece informações sobre direitos autorais de terceiros e licenças usadas neste produto.

link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2876856["Aviso para ONTAP 9.9,1"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2873871["Aviso para ONTAP 9.8"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2860921["Aviso para ONTAP 9.7"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2855145["Aviso para ONTAP 9.6"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2850702["Aviso para ONTAP 9.5"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2844310["Aviso para ONTAP 9.4"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2839209["Aviso para ONTAP 9.3"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2702054["Aviso para ONTAP 9.2"] link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2516795["Aviso para ONTAP 9.1"]
