---
permalink: online-help-96-97/concept_how_data_ontap_name_service_switch_configuration_works.html 
sidebar: sidebar 
keywords: ontap, name, service, switch, configuration, works, unix, system, online, help 
summary: O ONTAP armazena informações de configuração do serviço de nomes em uma tabela equivalente ao arquivo /etc/nsswitch.conf em sistemas UNIX. Você deve entender a função da tabela e como o ONTAP a usa para que você possa configurá-la adequadamente para o seu ambiente. 
---
= Sobre a configuração do switch de serviço de nome do ONTAP no Gerenciador de sistema - ONTAP 9 .7 e anterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP System Manager classic (disponível no ONTAP 9.7 e versões anteriores) armazena informações de configuração de serviço de nomes em uma tabela equivalente `/etc/nsswitch.conf` ao arquivo em sistemas UNIX. Você deve entender a função da tabela e como o ONTAP a usa para que você possa configurá-la adequadamente para o seu ambiente.

A tabela de switch de serviço de nome do ONTAP determina quais fontes de serviço de nome o ONTAP consulta para obter informações para um determinado tipo de informações de serviço de nome. O ONTAP mantém uma tabela de switch de serviço de nomes separada para cada SVM.



== Tipos de banco de dados

A tabela armazena uma lista de serviços de nomes separada para cada um dos seguintes tipos de banco de dados:

|===
| Tipo de banco de dados | Define fontes de serviço de nome para... | Fontes válidas são... 


 a| 
hosts
 a| 
Conversão de nomes de host para endereços IP
 a| 
ficheiros, dns



 a| 
grupo
 a| 
Procurar informações do grupo de utilizadores
 a| 
arquivos, nis, ldap



 a| 
passwd
 a| 
Procurar informações do utilizador
 a| 
arquivos, nis, ldap



 a| 
grupo de rede
 a| 
Procurar informações do netgroup
 a| 
arquivos, nis, ldap



 a| 
namemap
 a| 
Mapeando nomes de usuários
 a| 
ficheiros, ldap

|===


== Tipos de origem

As fontes especificam qual fonte de serviço de nomes usar para recuperar as informações apropriadas.

|===
| Especificar tipo de origem... | Para procurar informações em... | Gerenciado pelas famílias de comando... 


 a| 
ficheiros
 a| 
Arquivos de origem local
 a| 
`vserver services name-service unix-user`

`vserver services name-service unix-group`

`vserver services name-service netgroup`

`vserver services name-service dns hosts`



 a| 
nis
 a| 
Servidores NIS externos, conforme especificado na configuração do domínio NIS da SVM
 a| 
`vserver services name-service nis-domain`



 a| 
ldap
 a| 
Servidores LDAP externos, conforme especificado na configuração de cliente LDAP do SVM
 a| 
`vserver services name-service ldap`



 a| 
dns
 a| 
Servidores DNS externos conforme especificado na configuração DNS do SVM
 a| 
`vserver services name-service dns`

|===
Mesmo que você Planeje usar NIS ou LDAP para acesso a dados e autenticação de administração SVM, você ainda deve incluir `files` e configurar usuários locais como um fallback caso a autenticação NIS ou LDAP falhe.

*Informações relacionadas*

xref:task_editing_svm_settings.adoc[Editando configurações do SVM]
