---
permalink: online-help-96-97/task_editing_application.html 
sidebar: sidebar 
keywords: edit, application, online, help, provisioned, snapshot, copy 
summary: É possível editar uma aplicação provisionada para aumentar o tamanho do storage ou gerenciar as cópias Snapshot da aplicação. 
---
= Edite um aplicativo com o Gerenciador de sistema - ONTAP 9.7 e anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o ONTAP System Manager classic (disponível no ONTAP 9.7 e anterior) para editar uma aplicação provisionada a fim de aumentar para o tamanho do storage ou gerenciar as cópias Snapshot da aplicação.

.Sobre esta tarefa
Como administrador do cluster, depois de provisionar um aplicativo, você pode editá-lo para modificar o tamanho do armazenamento. Você também pode criar, restaurar ou excluir cópias Snapshot do aplicativo. O procedimento de exemplo a seguir descreve como editar um aplicativo *nas container*.

.Passos
. Clique em *aplicativos e camadas* > *aplicativos*
. Clique no nome da aplicação de contêiner nas.
+
[NOTE]
====
Se alguém adicionar novos aplicativos usando a CLI ou a API REST enquanto estiver exibindo a lista de aplicativos, não será possível exibir esses novos aplicativos ao rolar a lista.

====
+
A guia *Visão geral* da janela Detalhes do aplicativo: nas exibe as configurações do aplicativo.

. Clique em *Editar*.
+
O Edit nas Container: nas exibe a configuração atual de tamanho de armazenamento e o endereço *NFS Access - Grant Access to Host*.

. Modifique o valor *Storage Total Size*.
. No campo unidades de tamanho, selecione no menu suspenso para especificar as unidades de tamanho corretas (bytes, MB, GB ou TB).
. No campo *nível de serviço ONTAP*, selecione no menu suspenso para especificar o valor.
. Clique em *Salvar*.
. Navegue de volta para a janela *Application Details: nas* e selecione a guia **Snapshot Copies.
+
Uma lista de cópias Snapshot para esse aplicativo provisionado é exibida. Você pode usar o campo *pesquisar* para pesquisar cópias Snapshot por nome.

. Gerencie as cópias Snapshot executando as seguintes tarefas conforme necessário:
+
|===
| Tarefa | Ações 


 a| 
Criar
 a| 
Clique em *criar* para criar uma nova cópia Snapshot.



 a| 
Restaurar
 a| 
Clique nas caixas de verificação junto às cópias Snapshot que pretende restaurar e, em seguida, clique em *Restaurar*.



 a| 
Eliminar
 a| 
Clique nas caixas de verificação junto às cópias Snapshot que pretende eliminar e, em seguida, clique em *Eliminar*.

|===

