---
permalink: online-help-96-97/task_assigning_luns_to_storage_qos.html 
sidebar: sidebar 
keywords: qos, quality, service, assign, lun, storage, system, manager, lun, online, help, policy, group 
summary: 'Você pode usar o System Manager para limitar a taxa de transferência de LUNs atribuindo-os a grupos de políticas de qualidade do serviço (QoS) de storage. É possível atribuir QoS de storage a novos LUNs ou modificar detalhes de QoS de storage para LUNs que já estão atribuídos a um grupo de políticas.' 
---
= Atribua LUNs à QoS de storage com o System Manager - ONTAP 9.7 e versões anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o ONTAP System Manager classic (disponível no ONTAP 9.7 e anterior) para limitar a taxa de transferência de LUNs atribuindo-os a grupos de políticas de qualidade do serviço (QoS) de storage. É possível atribuir QoS de storage a novos LUNs ou modificar detalhes de QoS de storage para LUNs que já estão atribuídos a um grupo de políticas.

.Sobre esta tarefa
* Não é possível atribuir QoS de storage a um LUN se os seguintes objetos de storage forem atribuídos a um grupo de políticas:
+
** Volume pai do LUN
** Máquina virtual de storage pai (SVM) do LUN


* Você pode atribuir QoS de storage ou modificar os detalhes de QoS para um máximo de 10 LUNs simultaneamente.


.Passos
. Clique em *armazenamento* > *LUNs*.
. Na guia *Gerenciamento de LUN*, selecione um ou mais LUNs para os quais você deseja atribuir QoS de armazenamento.
. Clique em *QoS de armazenamento*.
. Na caixa de diálogo *Quality of Service Details* (Detalhes da qualidade do serviço), marque a caixa de seleção *Manage Storage Quality of Service* (Gerenciar qualidade do serviço de armazenamento) se desejar gerenciar o desempenho da carga de trabalho do LUN.
+
Se alguns dos LUNs selecionados já estiverem atribuídos a um grupo de políticas, as alterações feitas poderão afetar o desempenho desses LUNs.

. Crie um novo grupo de políticas de QoS de storage ou selecione um grupo de políticas existente para controlar o desempenho de entrada/saída (e/S) do LUN:
+
|===
| Se você quiser... | Faça isso... 


 a| 
Crie um novo grupo de políticas
 a| 
.. Selecione *novo Grupo de políticas*.
.. Especifique o nome do grupo de políticas.
.. Especifique o limite mínimo de taxa de transferência.
+
*** No System Manager 9,5, você pode definir o limite mínimo de taxa de transferência apenas com uma personalidade otimizada para All Flash baseada em performance. No System Manager 9,6, você também pode definir o limite mínimo de taxa de transferência para sistemas ONTAP Select Premium.
*** Não é possível definir o limite mínimo de taxa de transferência para volumes em um agregado habilitado para FabricPool.
*** Se você não especificar o valor mínimo da taxa de transferência ou se o valor mínimo da taxa de transferência estiver definido como 0, o sistema exibirá automaticamente "'nenhum'" como o valor.
+
Este valor é sensível a maiúsculas e minúsculas.



.. Especifique o limite máximo de taxa de transferência para garantir que a carga de trabalho dos objetos no grupo de políticas não exceda o limite de taxa de transferência especificado.
+
*** O limite mínimo de rendimento e o limite máximo de rendimento devem ser do mesmo tipo de unidade.
*** Se você não especificar o limite mínimo de taxa de transferência, poderá definir o limite máximo de taxa de transferência em IOPS e B/s, KB/s, MB/s e assim por diante.
*** Se você não especificar o valor máximo da taxa de transferência, o sistema exibirá automaticamente "'Unlimited'" como o valor e esse valor será sensível a maiúsculas e minúsculas.
+
A unidade especificada não afeta a taxa de transferência máxima.







 a| 
Selecione um grupo de políticas existente
 a| 
.. Selecione *Grupo de políticas existente* e clique em *escolha* para selecionar um grupo de políticas existente na caixa de diálogo Selecionar Grupo de políticas.
.. Especifique o limite mínimo de taxa de transferência.
+
*** No System Manager 9,5, você pode definir o limite mínimo de taxa de transferência apenas com uma personalidade otimizada para All Flash baseada em performance. No System Manager 9,6, você também pode definir o limite mínimo de taxa de transferência para sistemas ONTAP Select Premium.
*** Não é possível definir o limite mínimo de taxa de transferência para volumes em um agregado habilitado para FabricPool.
*** Se você não especificar o valor mínimo da taxa de transferência ou se o valor mínimo da taxa de transferência estiver definido como 0, o sistema exibirá automaticamente "'nenhum'" como o valor.
+
Este valor é sensível a maiúsculas e minúsculas.



.. Especifique o limite máximo de taxa de transferência para garantir que a carga de trabalho dos objetos no grupo de políticas não exceda o limite de taxa de transferência especificado.
+
*** O limite mínimo de rendimento e o limite máximo de rendimento devem ser do mesmo tipo de unidade.
*** Se você não especificar o limite mínimo de taxa de transferência, poderá definir o limite máximo de taxa de transferência em IOPS e B/s, KB/s, MB/s e assim por diante.
*** Se você não especificar o valor máximo da taxa de transferência, o sistema exibirá automaticamente "'Unlimited'" como o valor e esse valor será sensível a maiúsculas e minúsculas. A unidade que você especificar não afeta a taxa de transferência máxima.


+
Se o grupo de políticas for atribuído a mais de um objeto, a taxa de transferência máxima especificada será compartilhada entre os objetos.



|===
. *Opcional:* clique no link que especifica o número de LUNs para revisar a lista de LUNs selecionados e clique em *descarte* se quiser remover LUNs da lista.
+
O link é exibido somente quando vários LUNs são selecionados.

. Clique em *OK*.

