---
permalink: online-help-96-97/task_configuring_iscsi_protocol_on_svms.html 
sidebar: sidebar 
keywords: system, manager, iscsi, protocol, svm, online, help, lif, portset 
summary: 'Você pode configurar o protocolo iSCSI em uma máquina virtual de armazenamento (SVM) para fornecer acesso a dados em nível de bloco usando o System Manager. Você pode criar iSCSI LIFs e portsets e, em seguida, adicionar os LIFs aos portsets. Os LIFs são criados nos adaptadores mais adequados e são atribuídos a portsets para garantir a redundância do caminho dos dados.' 
---
= Configure o protocolo iSCSI em SVMs com o System Manager - ONTAP 9.7 e anterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o ONTAP System Manager classic (disponível no ONTAP 9.7 e anterior) para configurar o protocolo iSCSI em uma máquina virtual de storage (SVM) para fornecer acesso a dados em nível de bloco. Você pode criar iSCSI LIFs e portsets e, em seguida, adicionar os LIFs aos portsets. Os LIFs são criados nos adaptadores mais adequados e são atribuídos a portsets para garantir a redundância do caminho dos dados.

.Antes de começar
* A licença iSCSI tem de estar ativada no cluster.
+
Se o protocolo iSCSI não estiver ativado no SVM, você poderá usar a janela Editar Máquina Virtual de armazenamento para ativar o protocolo para o SVM.

* Todos os nós no cluster precisam estar íntegros.
* Cada nó deve ter pelo menos duas portas de dados e o estado da porta deve ser `up`.


.Sobre esta tarefa
* Pode configurar o protocolo iSCSI enquanto cria o SVM ou pode fazê-lo posteriormente.
* Agregados SnapLock não são considerados para criar volumes automaticamente.


.Passos
. Se não tiver configurado o protocolo iSCSI durante a criação do SVM, clique em *Storage* > *SVMs*.
. Selecione o SVM e clique em *Configurações do SVM*.
. No painel *Protocolos*, clique em *iSCSI*.
. *Opcional:* na seção *Acesso à rede*, especifique um alias para o destino iSCSI.
+
O número máximo de carateres para um nome de alias é 128. Se você não especificar um alias de destino, o nome SVM será usado como um alias.

. Especifique o número de iSCSI LIFs que podem ser atribuídos a um único nó.
+
O número mínimo de LIFs por nó é um. O número máximo é o mínimo de todas as portas no `up` estado entre os nós. Se o valor máximo for um número ímpar, o número par anterior é considerado como o valor máximo. Você pode escolher qualquer número par no intervalo de valores mínimo e máximo.

+
Um cluster de 4 nós tem node1, node2 e node3 com seis portas cada no estado e node4 com sete portas `up` no estado. `up` O valor máximo efetivo para o cluster é 6.

+
Se o número de LIFs que você deseja atribuir ao nó for superior a dois, você deve atribuir pelo menos um portset a cada LIF.

. Especifique os detalhes da rede, incluindo os detalhes da sub-rede, para criar iSCSI LIFs:
+
|===
| Se você quiser... | Então... 


 a| 
Especifique o endereço IP usando uma sub-rede
 a| 
.. Selecione *usando uma sub-rede*.
.. Na caixa de diálogo Adicionar detalhes, selecione a sub-rede a partir da qual o endereço IP deve ser atribuído.
+
Para LIFs entre clusters, apenas as sub-redes associadas ao espaço IPspace selecionado são exibidas.

.. Se quiser atribuir um endereço IP específico à interface, selecione *Use um endereço IP específico* e digite o endereço IP.
+
O endereço IP especificado é adicionado à sub-rede se o endereço IP ainda não estiver presente no intervalo de sub-rede.

.. Clique em *OK*.




 a| 
Especifique o endereço IP manualmente sem usar uma sub-rede
 a| 
.. Selecione *sem uma sub-rede*.
.. Na caixa de diálogo Adicionar detalhes, execute as seguintes etapas:
+
... Especifique o endereço IP e a máscara ou prefixo da rede.
... Opcional: Especifique o gateway.
... Se não pretender utilizar o valor predefinido para o campo destino, especifique um novo valor de destino.
+
Se você não especificar um valor de destino, o campo destino será preenchido com o valor padrão com base na família do endereço IP.



+
Se uma rota não existir, uma nova rota é criada automaticamente com base no gateway e no destino.

.. Clique em *OK*.


|===
. Selecione o domínio de broadcast.
. Selecione o tipo de adaptador.
+
Se você tiver placas NIC configuradas no cluster, selecione *NIC*.

+
Se você tiver placas CNS configuradas no cluster, selecione *CNA*.

+
Se você tiver o ifgrps configurado no cluster, selecione *Grupo de interfaces*.

+
[NOTE]
====
A porta ifgrp deve ser adicionada no domínio de broadcast.

====
. *Opcional:* provisione um LUN para armazenamento iSCSI ao configurar o protocolo iSCSI especificando o tamanho do LUN, o tipo de SO para o LUN e os detalhes do iniciador do host.
. Se quiser verificar ou modificar a configuração dos iSCSI LIFs gerados automaticamente, selecione *Rever ou Modificar configuração LIFs (Configurações avançadas)*.
+
Você pode modificar apenas o nome LIF e a porta inicial. Por padrão, os portsets são definidos para o valor mínimo. Você deve especificar entradas exclusivas. Se você especificar nomes de LIF duplicados, o System Manager anexará valores numéricos ao nome de LIF duplicado.

+
Com base no portset selecionado, os LIFs são distribuídos pelos portsets usando um método round-robin para garantir redundância em caso de falha de nó ou falha de porta.

. Clique em *Enviar e continuar*.


.Resultados
Os iSCSI LIFs e portsets são criados com a configuração especificada. Os LIFs são distribuídos entre os portsets com base no portset selecionado. O serviço iSCSI é iniciado se todas as LIFs forem criadas com êxito.

Se a criação de LIF falhar, você pode criar os LIFs usando a janela interfaces de rede, anexar os LIFs aos portsets usando a janela LUNs e, em seguida, iniciar o serviço iSCSI usando a janela iSCSI.
