---
permalink: online-help-96-97/task_creating_snapshot_copies_outside_defined_schedule.html 
sidebar: sidebar 
keywords: create, snapshot, copy, outside, defined, schedule, online, help, system, manager 
summary: Você pode usar o System Manager para criar uma cópia Snapshot de um volume fora de uma programação definida para capturar o estado do sistema de arquivos em um determinado momento. 
---
= Crie cópias Snapshot fora de uma programação definida com o System Manager - ONTAP 9.7 e anterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o ONTAP System Manager classic (disponível no ONTAP 9.7 e anterior) para criar uma cópia Snapshot de um volume fora de uma programação definida para capturar o estado do sistema de arquivos em um ponto específico no tempo.

.Passos
. Clique em *Storage* > *volumes*.
. No menu suspenso no campo *SVM*, selecione *All SVMs*.
. Selecione o volume na lista de volumes.
. Clique em *mais ações* > *Gerenciar capturas instantâneas* > *criar*.
. Na caixa de diálogo *criar cópia Instantânea*, se você quiser alterar o nome padrão, especifique um novo nome para a cópia Instantânea.
+
Os carateres válidos são carateres ASCII, numerais, hífens (-), sublinhados (_), pontos (.) e o símbolo de mais (.).

+
O nome padrão de uma cópia Snapshot consiste no nome do volume e no carimbo de data/hora.

. Clique em *criar*.
. Verifique se a cópia Snapshot que você criou está incluída na lista de cópias Snapshot na guia *cópias Snapshot*.


*Informações relacionadas*

xref:reference_volumes_window.adoc[Janela volumes]
