---
permalink: online-help-96-97/task_accessing_cluster_by_using_system_manager_by_using_browser.html 
sidebar: sidebar 
keywords: online, help, access, cluster, ontap, system, manager, graphic, interface, cli, command, line, interface 
summary: 'Se você preferir usar uma interface gráfica em vez da interface de linha de comando (CLI) para acessar e gerenciar um cluster, você pode fazer isso usando o Gerenciador de sistema do ONTAP, que está incluído no ONTAP como um serviço da Web, é habilitado por padrão e é acessível usando um navegador.' 
---
= Acessar um cluster usando a interface gráfica baseada no navegador do Gerenciador de sistema do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você preferir usar uma interface gráfica em vez da interface de linha de comando (CLI) para acessar e gerenciar um cluster, você pode fazer isso usando o Gerenciador de sistema do ONTAP, que está incluído no ONTAP como um serviço da Web, é habilitado por padrão e é acessível usando um navegador.

.Antes de começar
* Você deve ter uma conta de usuário de cluster configurada com a `admin` função e os `http` tipos de aplicativo , `ontapi` e . `console`
* Você deve ter ativado cookies e dados do site no navegador.


.Sobre esta tarefa
Você pode usar um LIF de gerenciamento de clusters ou um LIF de gerenciamento de nós para acessar o Gerenciador de sistema do ONTAP. Para ter acesso ininterrupto ao Gerenciador de sistemas do ONTAP, você deve usar um LIF de gerenciamento de clusters.

.Passos
. Aponte o navegador da Web para o endereço IP do LIF de gerenciamento de cluster:
+
** Se você estiver usando IPv4: `+https://cluster-mgmt-LIF+`
** Se você estiver usando o IPv6: `https://[cluster-mgmt-LIF]` Somente HTTPS é suportado para o acesso do navegador do Gerenciador de sistema do ONTAP.


+
Se o cluster usar um certificado digital autoassinado, o navegador pode exibir um aviso indicando que o certificado não é confiável. Você pode reconhecer o risco de continuar o acesso ou instalar um certificado digital assinado pela autoridade de certificação (CA) no cluster para autenticação do servidor.

. Se você tiver configurado um banner de acesso usando a CLI, leia a mensagem exibida na caixa de diálogo *Aviso* e escolha a opção necessária para prosseguir.
+
Esta opção não é suportada em sistemas nos quais a autenticação SAML (Security Assertion Markup Language) está ativada.

+
** Se você não quiser continuar, clique em *Cancelar* e feche o navegador.
** Se pretender continuar, clique em *OK* para navegar para a página de início de sessão do Gestor do sistema ONTAP.


. Faça login no Gerenciador de sistemas do ONTAP usando suas credenciais de administrador de cluster.


*Informações relacionadas*

https://docs.netapp.com/ontap-9/index.jsp["Centro de Documentação do ONTAP 9"]
