---
permalink: nfs-config-esxi/task_installing_virtual_storage_console_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: configuration, provision, task, storage, esxi, host, plug-in, vcenter, server, install 
summary: O para automatiza muitas das tarefas de configuração e provisionamento necessárias para usar o armazenamento com um host ESXi. É um plug-in do vCenter Server. 
---
= Instale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Virtual Storage Console para automatiza muitas das tarefas de configuração e provisionamento necessárias para usar o armazenamento com um host ESXi. É um plug-in do vCenter Server.

.Antes de começar
Você deve ter credenciais de administrador no vCenter Server usadas para gerenciar o host ESXi.

.Sobre esta tarefa
* O Virtual Storage Console é instalado como um dispositivo virtual que inclui o Virtual Storage Console, o provedor vStorage APIs for Storage Awareness (VASA) e o Storage Replication Adapter (SRA) para os recursos do VMware vSphere.


.Passos
. Baixe a versão que é suportada para sua configuração, como mostrado na ferramenta Matriz de interoperabilidade.
+
https://mysupport.netapp.com/site/global/dashboard["Suporte à NetApp"]

. Implante o dispositivo virtual e configure-o seguindo as etapas em _Guia de implantação e configuração_.

