---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, linux, server, configuration, red hat enterprise linux 
summary: Você pode configurar rapidamente o serviço FC em uma máquina virtual de armazenamento, provisionar um LUN e disponibilizar o LUN usando um adaptador de barramento de host FC em um servidor Red Hat Enterprise Linux. 
---
= Visão geral da configuração FC para Red Hat Enterprise Linux
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar rapidamente o serviço FC em uma máquina virtual de storage (SVM), provisionar um LUN e disponibilizar o LUN usando um adaptador de barramento de host FC (HBA) em um servidor Red Hat Enterprise Linux usando a interface clássica do ONTAP System Manager (ONTAP 9.7 e anterior).

Use este procedimento para configurar o serviço FC em uma SVM se:

* O host está executando uma versão suportada do Red Hat Enterprise Linux 6,4 ou posterior.
* Você está usando HBAs e switches FC tradicionais.
+

NOTE: O Fibre Channel over Ethernet (FCoE) não é coberto neste procedimento.

* Você tem pelo menos duas portas de destino FC disponíveis em cada nó do cluster. Portas integradas FC e UTA2 (também chamadas de "CNA"), bem como alguns adaptadores, são configuráveis. A configuração dessas portas é feita na interface de linha de comando (CLI) do ONTAP e não é abordada neste procedimento.
* Você não está configurando a inicialização FC SAN.


Se essas suposições não estiverem corretas para sua situação, você deverá ver os seguintes recursos:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["Administração da SAN"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["Configuração SAN"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Linux Unified Host Utilities 7,1 Instalação"^]




== Outras maneiras de fazer isso em ONTAP

|===


| Para executar estas tarefas com... | Consulte... 


| O Gerenciador de sistema redesenhado (disponível com o ONTAP 9.7 e posterior) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_linux.html["Provisione storage SAN para servidores Linux"^] 


| A interface de linha de comando (CLI) do ONTAP | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Fluxo de trabalho de configuração LUN com a CLI"^] 
|===