---
permalink: iscsi-config-rhel/task_verifying_that_host_can_write_to_read_fom_lun.html 
sidebar: sidebar 
keywords: multipath, device, verify, host, data, verify that the host can write to and read from a multipath device 
summary: Antes de usar um dispositivo multipath, verifique se o host pode gravar dados no dispositivo multipath e lê-los de volta. 
---
= Verifique se o host pode gravar e ler em um dispositivo multipath
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar um dispositivo multipath, verifique se o host pode gravar dados no dispositivo multipath e lê-los de volta.

.Antes de começar
O DM-Multipath deve ser configurado no host Linux para os nós de cluster de storage que você está acessando.

.Sobre esta tarefa
Se o nó do cluster de storage ao qual o dispositivo multipath corresponde puder ser repassado para o nó do parceiro, você deve verificar a leitura dos dados enquanto o nó estiver com falha. Essa verificação pode não ser possível se o cluster de armazenamento estiver em uso em produção.

.Passos
. Execute alguma I/o no dispositivo multipath especificado:
+
`dd if=/dev/zero of=<multipath_device_name\>`

. Verifique se a e/S está em execução no dispositivo multipath, especificando o número de segundos para atualizar estatísticas (por exemplo, a cada dois segundos, como mostrado):
+
`iostat 2`

+
Quando a e/S está sendo executada no dispositivo multipath, você pode ver a alteração de saída dos vários contadores de e/S dinamicamente, indicando que a e/S está sendo executada com sucesso no dispositivo multipath.

+
[listing]
----
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
            0.00    0.00    0.01    0.00    0.00   99.98

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.18         1.34         2.29     832606    1428026
dm-0              0.37         1.29         2.29     801530    1427984
dm-1              0.00         0.00         0.00       2576          0
dm-2              0.00         0.00         0.00       1770         24
sdd               0.17         1.18        17.87     734688   11128584
sde               0.17         1.18        18.01     734560   11219016
sdf               0.00         0.00         0.00       1344          0
sdg               0.00         0.00         0.00       1344          0
dm-3              0.68         4.71        71.96    2932496   44816008
sdh               0.17         1.18        18.22     734360   11343920
sdi               0.17         1.18        17.86     734272   11124488
sdj               0.00         0.00         0.00       1344          0
sdk               0.00         0.00         0.00       1344          0
.............
----
. Se possível, execute o `takeover` comando no nó do cluster de armazenamento:
+
`storage failover takeover -ofnode <node_name\>`

. Verifique se e/S ainda está em execução no dispositivo multipath executando novamente o `iostat` comando.
. Execute o `giveback` comando no nó do cluster de storage:
+
`storage failover giveback -ofnode <node_name\>`

. Verifique `iostat` a saída para verificar se a e/S ainda está em execução.




== O que fazer a seguir

Se algum dos testes falhar, verifique se o serviço iSCSI está em execução e verifique novamente a configuração DM-Multipath e os caminhos iSCSI para o dispositivo multipath.
