---
permalink: iscsi-config-rhel/task_discovering_new_scsi_devices_dm_multipath_devices.html 
sidebar: sidebar 
keywords: 'lun, storage, cluster, linux, scsi, device, i/o, path, dm-multipath, multipath, manual, discover new scsi devices (luns) and multipath devices' 
summary: 'Os LUNs no cluster de armazenamento aparecem para o host Linux como dispositivos SCSI, que são caminhos de e/S que o DM-Multipath agrega em um novo dispositivo, chamado de dispositivo multipath. O host não deteta automaticamente novos dispositivos SCSI (LUNs) adicionados ao seu sistema. Você deve revê-los manualmente para descobri-los.' 
---
= Descubra novos dispositivos SCSI (LUNs) e dispositivos multipath
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os LUNs no cluster de armazenamento aparecem para o host Linux como dispositivos SCSI, que são caminhos de e/S que o DM-Multipath agrega em um novo dispositivo, chamado de dispositivo multipath. O host não deteta automaticamente novos dispositivos SCSI (LUNs) adicionados ao seu sistema. Você deve revê-los manualmente para descobri-los.

.Antes de começar
Você deve ter uma cópia `rescan` do script, que está no `sg3_utils` pacote que faz parte da distribuição do sistema operacional Linux.

.Passos
. Descubra novos dispositivos SCSI (LUNs) e crie os dispositivos multipath correspondentes para os LUNs:
+
`/usr/bin/rescan-scsi-bus.sh`

. Verifique a configuração DM-Multipath:
+
`multipath -ll`

+
Isso exibe o seguinte tipo de saída, listando as configurações recomendadas para cada LUN NetApp:

+
[listing]
----
3600a0980324666546e2b443251655177 dm-2 NETAPP,LUN C-Mode
size=10G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:1:0 sdb 8:16  active ready  running
| |- 0:0:0:0 sda 8:0   active ready  running
| |- 1:0:0:0 sde 8:64  active ready  running
| `- 1:0:1:0 sdf 8:80  active ready  running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:3:0 sdd 8:48  active ready  running
  |- 1:0:3:0 sdh 8:112 active ready  running
  |- 0:0:2:0 sdc 8:32  active ready  running
  `- 1:0:2:0 sdg 8:96  active ready  running
----

