---
permalink: peering/reference_prerequisites_for_cluster_peering.html 
sidebar: sidebar 
keywords: cluster, peer, connectivity, port, ip, address, subnet, firewall, cluster-naming, requirement, prerequisite, prerequisite for cluster peering 
summary: 'Antes de configurar o peering de cluster usando a interface "clássica" do Gerenciador de sistema do ONTAP com o ONTAP 9.7 ou anterior, você deve confirmar que os requisitos de conetividade, porta, endereço IP, sub-rede, firewall e nomenclatura de cluster são atendidos.' 
---
= Pré-requisitos para peering de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar o peering de cluster usando a interface _classic_ do Gerenciador de sistema do ONTAP com o ONTAP 9.7 ou anterior, você deve confirmar que os requisitos de conetividade, porta, endereço IP, sub-rede, firewall e nomenclatura de cluster são atendidos.



== Requisitos de conetividade

Cada LIF no cluster local deve ser capaz de se comunicar com cada LIF entre clusters no cluster remoto.

Embora não seja necessário, geralmente é mais simples configurar os endereços IP usados para LIFs entre clusters na mesma sub-rede. Os endereços IP podem residir na mesma sub-rede que os LIFs de dados ou em uma sub-rede diferente. A sub-rede usada em cada cluster deve atender aos seguintes requisitos:

* A sub-rede deve ter endereços IP suficientes disponíveis para alocar a um LIF entre clusters por nó.
+
Por exemplo, em um cluster de seis nós, a sub-rede usada para comunicação entre clusters deve ter seis endereços IP disponíveis.



Cada nó deve ter um LIF entre clusters com um endereço IP na rede entre clusters.

LIFs podem ter um endereço IPv4 ou um endereço IPv6 entre clusters.

[NOTE]
====
O ONTAP 9 permite que você migre suas redes de peering de IPv4 para IPv6, permitindo opcionalmente que ambos os protocolos estejam presentes simultaneamente nas LIFs entre clusters. Em versões anteriores, todas as relações entre clusters para um cluster inteiro eram IPv4 ou IPv6. Isso significava que a mudança de protocolos era um evento potencialmente disruptivo.

====


== Requisitos portuários

Você pode usar portas dedicadas para comunicação entre clusters ou compartilhar portas usadas pela rede de dados. As portas devem atender aos seguintes requisitos:

* Todas as portas usadas para se comunicar com um determinado cluster remoto devem estar no mesmo espaço IPspace.
+
Você pode usar vários IPspaces para fazer pares com vários clusters. A conetividade de malha completa em pares é necessária apenas dentro de um espaço IPspace.

* O domínio de broadcast usado para comunicação entre clusters deve incluir pelo menos duas portas por nó para que a comunicação entre clusters possa fazer failover de uma porta para outra porta.
+
As portas adicionadas a um domínio de broadcast podem ser portas de rede físicas, VLANs ou grupos de interface (ifgrps).

* Todas as portas devem ser cabeadas.
* Todas as portas devem estar em um estado saudável.
* As configurações de MTU das portas devem ser consistentes.




== Requisitos de firewall

Os firewalls e a política de firewall entre clusters devem permitir os seguintes protocolos:

* Serviço ICMP
* TCP para os endereços IP de todos os LIFs entre clusters nas portas 10000, 11104 e 11105
* HTTPS bidirecional entre os LIFs entre clusters
+
Embora o HTTPS não seja necessário quando você configura o peering de cluster usando a CLI, o HTTPS é necessário mais tarde se você usar o Gerenciador de sistema do ONTAP para configurar a proteção de dados.



A política de firewall predefinida `intercluster` permite o acesso através do protocolo HTTPS e de todos os endereços IP (0,0.0,0/0). Você pode modificar ou substituir a política, se necessário.

.Informações relacionadas
https://docs.netapp.com/us-en/ontap/data-protection/index.html["Proteção de dados"]
