---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: 'Com a interface clássica do ONTAP System Manager (ONTAP 9.7 e anterior), é possível configurar rapidamente o acesso SMB/CIFS a um novo volume em uma máquina virtual de storage (SVM) nova ou existente.' 
---
= Visão geral da configuração SMB/CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Com a interface clássica do ONTAP System Manager (ONTAP 9.7 e anterior), é possível configurar rapidamente o acesso SMB/CIFS a um novo volume em uma máquina virtual de storage (SVM) nova ou existente.

Utilize este procedimento se pretender configurar o acesso a um volume da seguinte forma:

* Você quer usar as práticas recomendadas, não explorar todas as opções disponíveis.
* Sua rede de dados usa o IPspace padrão, o domínio de broadcast padrão e o grupo de failover padrão.
+
Se sua rede de dados for plana, usar esses objetos padrão garante que LIFs falharão corretamente em caso de falha de link. Se você não estiver usando os objetos padrão, consulte o https://docs.netapp.com/us-en/ontap/networking/index.html["Documentação de gerenciamento de rede"^] para obter informações sobre como configurar o failover de caminho LIF.

* As permissões de arquivo NTFS serão usadas para proteger o novo volume.


Se pretender obter detalhes sobre a gama de capacidades do protocolo SMB do ONTAP, consulte o link:https://docs.netapp.com/us-en/ontap/smb-admin/index.html["Visão geral de referência SMB"^].



== Outras maneiras de fazer isso em ONTAP

|===


| Para executar estas tarefas com... | Consulte... 


| O Gerenciador de sistema redesenhado (disponível com o ONTAP 9.7 e posterior) | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html["Provisione storage nas para servidores Windows usando SMB"^] 


| A interface da linha de comando ONTAP | link:https://docs.netapp.com/us-en/ontap/smb-config/index.html["Visão geral da configuração SMB com a CLI"^] 
|===