---
permalink: expansion/task_generating_autosupport_message_about_completing_expansion.html 
sidebar: sidebar 
keywords: expand, cluster, autosupport, indicate, expansion, process, complete, message, communicate, internal, external, support, staff, complete, troubleshoot, generate, generate an autosupport, message about completing expansion 
summary: Depois de expandir um cluster, você deve enviar uma mensagem AutoSupport para indicar que o processo de expansão está concluído. 
---
= Gerar uma mensagem AutoSupport sobre como concluir a expansão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de expandir um cluster, você deve enviar uma mensagem AutoSupport para indicar que o processo de expansão está concluído. Esta mensagem comunica à equipe de suporte interna e externa que a expansão está concluída e atua como um carimbo de data/hora para qualquer solução de problemas que possa ser necessária posteriormente.

.Antes de começar
O AutoSupport deve ser configurado.

.Passos
. Para cada nó no cluster, envie uma mensagem AutoSupport usando o `system node autosupport invoke` comando.
+
Você deve emitir a mensagem uma vez para cada nó no cluster, incluindo os nós recém-adicionados.

+
Se você adicionou dois nós a um cluster de dois nós, deverá enviar a mensagem quatro vezes.

+
[listing]
----
cluster1::> system node autosupport invoke -node * -message "cluster expansion complete" -type all
The AutoSupport was successfully invoked on node "cluster1-1". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
The AutoSupport was successfully invoked on node "cluster1-2". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
The AutoSupport was successfully invoked on node "cluster1-3". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
The AutoSupport was successfully invoked on node "cluster1-4". To view the status
of the AutoSupport, use the "system node autosupport history show" command.
Note: It may take several minutes for the AutoSupport to appear in the history list.
4 entries were acted on.
----

